### ISSUE TITLE
[BUG] Hamburger Menu 

### ISSUE THREAD

**Issue by Saurav-Pant** [jordihales/hypercolor#59] opened 2023-09-17 16:48 UTC
Bug 1 
When opening the hamburger menu, the cross (close) icon is not present, which affects the user experience.

Bug 2

There is a bug where if a user is on a small device and clicks the hamburger menu to show navigation links and then switches to a large screen, the navigation links are displayed twice on the screen.

https://github.com/jordihales/hypercolor/assets/103263909/4821b60e-1c61-4771-8ecb-026dfb3e79e6
![cross sign](https://github.com/jordihales/hypercolor/assets/103263909/6ad89c17-3bd8-40e9-a8c8-fad4e614c6a5)

If you believe that these issues need to be resolved, please assign them to me

**Comment by markmead** [comment] 2023-10-04 08:23
Hi @Saurav-Pant 

Thanks for creating the issue.

1. Not a bug, the user can click the hamburger icon again to close it.
2. Not something that needs addressing as this situation is not very common.

**Closed by markmead** 2023-10-04 08:23 UTC
